### ISSUE TITLE
What to return 

### ISSUE THREAD

**Issue by munyagz** [golclinics/micropilot-entry-challenge#129]
What do i return when:

1. The answer is a complex solution?
2. X1 and X2 are equal?

**Comment by profnandaa** [comment]
I can see one person here that knows his maths! :) We'd not thought of that but perhaps for complex one, raising an exception is ok for now.

**Comment by profnandaa** [comment]
We have updated the challenge to a new one but you had a point there, needed some clarification.

**Comment by munyagz** [comment]
> We have updated the challenge to a new one but you had a point there, needed some clarification.

Am I required to do the new challenge?
